// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// TooltipPlacement names the edge of the trigger the panel sits against.
type TooltipPlacement string

const (
	TooltipTop    TooltipPlacement = "top"
	TooltipRight  TooltipPlacement = "right"
	TooltipLeft   TooltipPlacement = "left"
	TooltipBottom TooltipPlacement = "bottom"
)

// TooltipProps configures Tooltip. The panel is revealed by hover on an
// ancestor, so the element that wraps both the trigger and the tooltip must
// carry "group relative" — the tooltip positions itself against that ancestor
// and has no way to add the classes itself.
type TooltipProps struct {
	// Empty places the panel above the trigger.
	Placement TooltipPlacement
	// Width is a Tailwind width class such as "w-48". Empty lets the panel
	// size to its content, which is what a one-line label wants.
	Width string
}

func Tooltip(props TooltipProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{tooltipPanelClass(props.Placement), props.Width}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div role=\"tooltip\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/tooltip.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// The placement classes are spelled out as whole literals rather than
// assembled from parts, because Tailwind finds classes by scanning source
// text: a class built by concatenation exists only at runtime and would be
// missing from the stylesheet.
func tooltipPanelClass(placement TooltipPlacement) string {
	switch placement {
	case TooltipRight:
		return tooltipBaseClass + " left-full top-1/2 ml-2 -translate-y-1/2"
	case TooltipLeft:
		return tooltipBaseClass + " right-full top-1/2 mr-2 -translate-y-1/2"
	case TooltipTop:
		return tooltipBaseClass + " bottom-full left-1/2 mb-2 -translate-x-1/2"
	default:
		return tooltipBaseClass + " top-full left-1/2 mt-2 -translate-x-1/2"
	}
}

// pointer-events-none keeps a panel that overlaps a neighbouring control from
// swallowing clicks meant for it.
const tooltipBaseClass = "pointer-events-none invisible absolute z-10 rounded bg-surface p-2 text-xs text-text opacity-0 shadow-md transition-opacity group-hover:visible group-hover:opacity-100"

var _ = templruntime.GeneratedTemplate
