// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RankedItem struct {
	ID             int64
	Label          string
	Sublabel       string
	SourceUrl      string
	SourceImageUrl string
	ImageUrl       string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Ranking struct {
	ID          int64
	Slug        uuid.UUID
	UserID      *int64
	Title       string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RankingItem struct {
	RankingID    int64
	RankedItemID int64
	CreatedAt    pgtype.Timestamptz
}

type RankingTier struct {
	ID            int64
	RankingID     int64
	Label         string
	Position      int32
	Color         string
	AllowMultiple bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type RankingTierItem struct {
	RankingTierID int64
	RankedItemID  int64
	Position      int32
	CreatedAt     pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID            int64
	Email         string
	PasswordHash  string
	EmailVerified bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	LastLoginAt   pgtype.Timestamptz
}
