// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rankings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRanking = `-- name: CreateRanking :one
INSERT INTO rankings (name, description, user_id)
VALUES ($1, $2, $3)
RETURNING id, uuid, created_at, updated_at, name, description, user_id
`

type CreateRankingParams struct {
	Name        string
	Description string
	UserID      int64
}

func (q *Queries) CreateRanking(ctx context.Context, arg CreateRankingParams) (Ranking, error) {
	row := q.db.QueryRow(ctx, createRanking, arg.Name, arg.Description, arg.UserID)
	var i Ranking
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const deleteRanking = `-- name: DeleteRanking :exec
DELETE FROM rankings WHERE id = $1
`

func (q *Queries) DeleteRanking(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRanking, id)
	return err
}

const getRankingByUUID = `-- name: GetRankingByUUID :one
SELECT id, uuid, created_at, updated_at, name, description, user_id FROM rankings WHERE uuid = $1
`

func (q *Queries) GetRankingByUUID(ctx context.Context, argUuid uuid.UUID) (Ranking, error) {
	row := q.db.QueryRow(ctx, getRankingByUUID, argUuid)
	var i Ranking
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const listRankingsByUser = `-- name: ListRankingsByUser :many
SELECT id, uuid, created_at, updated_at, name, description, user_id FROM rankings WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListRankingsByUser(ctx context.Context, userID int64) ([]Ranking, error) {
	rows, err := q.db.Query(ctx, listRankingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ranking
	for rows.Next() {
		var i Ranking
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRanking = `-- name: UpdateRanking :one
UPDATE rankings
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, uuid, created_at, updated_at, name, description, user_id
`

type UpdateRankingParams struct {
	ID          int64
	Name        string
	Description string
}

func (q *Queries) UpdateRanking(ctx context.Context, arg UpdateRankingParams) (Ranking, error) {
	row := q.db.QueryRow(ctx, updateRanking, arg.ID, arg.Name, arg.Description)
	var i Ranking
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.UserID,
	)
	return i, err
}
