// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"
)

const clearRankingPublicSlug = `-- name: ClearRankingPublicSlug :exec
UPDATE ranking_shares
SET is_public = false, public_slug = NULL
WHERE ranking_id = $1 AND user_id IS NULL AND email IS NULL
`

func (q *Queries) ClearRankingPublicSlug(ctx context.Context, rankingID int64) error {
	_, err := q.db.Exec(ctx, clearRankingPublicSlug, rankingID)
	return err
}

const createEmailShare = `-- name: CreateEmailShare :one
INSERT INTO ranking_shares (ranking_id, email, role)
VALUES ($1, $2, $3)
RETURNING id, created_at, role, is_public, public_slug, user_id, email, ranking_id
`

type CreateEmailShareParams struct {
	RankingID int64
	Email     *string
	Role      RankingShareRole
}

func (q *Queries) CreateEmailShare(ctx context.Context, arg CreateEmailShareParams) (RankingShare, error) {
	row := q.db.QueryRow(ctx, createEmailShare, arg.RankingID, arg.Email, arg.Role)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}

const deleteRankingShare = `-- name: DeleteRankingShare :exec
DELETE FROM ranking_shares WHERE id = $1
`

func (q *Queries) DeleteRankingShare(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRankingShare, id)
	return err
}

const getRankingShareByID = `-- name: GetRankingShareByID :one
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares WHERE id = $1
`

func (q *Queries) GetRankingShareByID(ctx context.Context, id int64) (RankingShare, error) {
	row := q.db.QueryRow(ctx, getRankingShareByID, id)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}

const getRankingShareByPublicSlug = `-- name: GetRankingShareByPublicSlug :one
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares WHERE public_slug = $1
`

func (q *Queries) GetRankingShareByPublicSlug(ctx context.Context, publicSlug *string) (RankingShare, error) {
	row := q.db.QueryRow(ctx, getRankingShareByPublicSlug, publicSlug)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}

const getRankingShareByUserAndRanking = `-- name: GetRankingShareByUserAndRanking :one
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares WHERE user_id = $1 AND ranking_id = $2
`

type GetRankingShareByUserAndRankingParams struct {
	UserID    *int64
	RankingID int64
}

func (q *Queries) GetRankingShareByUserAndRanking(ctx context.Context, arg GetRankingShareByUserAndRankingParams) (RankingShare, error) {
	row := q.db.QueryRow(ctx, getRankingShareByUserAndRanking, arg.UserID, arg.RankingID)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}

const listEmailSharesForRanking = `-- name: ListEmailSharesForRanking :many
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares
WHERE ranking_id = $1 AND (email IS NOT NULL OR user_id IS NOT NULL)
ORDER BY created_at
`

func (q *Queries) ListEmailSharesForRanking(ctx context.Context, rankingID int64) ([]RankingShare, error) {
	rows, err := q.db.Query(ctx, listEmailSharesForRanking, rankingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingShare
	for rows.Next() {
		var i RankingShare
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Role,
			&i.IsPublic,
			&i.PublicSlug,
			&i.UserID,
			&i.Email,
			&i.RankingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingSharesForRanking = `-- name: ListRankingSharesForRanking :many
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares WHERE ranking_id = $1 ORDER BY created_at
`

func (q *Queries) ListRankingSharesForRanking(ctx context.Context, rankingID int64) ([]RankingShare, error) {
	rows, err := q.db.Query(ctx, listRankingSharesForRanking, rankingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingShare
	for rows.Next() {
		var i RankingShare
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Role,
			&i.IsPublic,
			&i.PublicSlug,
			&i.UserID,
			&i.Email,
			&i.RankingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRankingShareUserID = `-- name: UpdateRankingShareUserID :exec
UPDATE ranking_shares SET user_id = $2 WHERE id = $1
`

type UpdateRankingShareUserIDParams struct {
	ID     int64
	UserID *int64
}

func (q *Queries) UpdateRankingShareUserID(ctx context.Context, arg UpdateRankingShareUserIDParams) error {
	_, err := q.db.Exec(ctx, updateRankingShareUserID, arg.ID, arg.UserID)
	return err
}

const upsertRankingLinkShare = `-- name: UpsertRankingLinkShare :one
INSERT INTO ranking_shares (ranking_id, is_public, public_slug)
VALUES ($1, true, $2)
ON CONFLICT (ranking_id) WHERE user_id IS NULL AND email IS NULL
DO UPDATE SET is_public = true, public_slug = $2
RETURNING id, created_at, role, is_public, public_slug, user_id, email, ranking_id
`

type UpsertRankingLinkShareParams struct {
	RankingID  int64
	PublicSlug *string
}

// Performantly create unique public share sicne wecan rely on the constraint
// to do nothing if a share already exists.
func (q *Queries) UpsertRankingLinkShare(ctx context.Context, arg UpsertRankingLinkShareParams) (RankingShare, error) {
	row := q.db.QueryRow(ctx, upsertRankingLinkShare, arg.RankingID, arg.PublicSlug)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}
