// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"
)

const clearRankingPublicSlug = `-- name: ClearRankingPublicSlug :exec
UPDATE ranking_shares
SET is_public = false, public_slug = NULL
WHERE ranking_id = $1 AND user_id IS NULL AND email IS NULL
`

func (q *Queries) ClearRankingPublicSlug(ctx context.Context, rankingID int64) error {
	_, err := q.db.Exec(ctx, clearRankingPublicSlug, rankingID)
	return err
}

const getRankingShareByPublicSlug = `-- name: GetRankingShareByPublicSlug :one
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares WHERE public_slug = $1
`

func (q *Queries) GetRankingShareByPublicSlug(ctx context.Context, publicSlug *string) (RankingShare, error) {
	row := q.db.QueryRow(ctx, getRankingShareByPublicSlug, publicSlug)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}

const listRankingSharesForRanking = `-- name: ListRankingSharesForRanking :many
SELECT id, created_at, role, is_public, public_slug, user_id, email, ranking_id FROM ranking_shares WHERE ranking_id = $1 ORDER BY created_at
`

func (q *Queries) ListRankingSharesForRanking(ctx context.Context, rankingID int64) ([]RankingShare, error) {
	rows, err := q.db.Query(ctx, listRankingSharesForRanking, rankingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingShare
	for rows.Next() {
		var i RankingShare
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Role,
			&i.IsPublic,
			&i.PublicSlug,
			&i.UserID,
			&i.Email,
			&i.RankingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRankingLinkShare = `-- name: UpsertRankingLinkShare :one
INSERT INTO ranking_shares (ranking_id, is_public, public_slug)
VALUES ($1, true, $2)
ON CONFLICT (ranking_id) WHERE user_id IS NULL AND email IS NULL
DO UPDATE SET is_public = true, public_slug = $2
RETURNING id, created_at, role, is_public, public_slug, user_id, email, ranking_id
`

type UpsertRankingLinkShareParams struct {
	RankingID  int64
	PublicSlug *string
}

// Performantly create unique public share sicne wecan rely on the constraint
// to do nothing if a share already exists.
func (q *Queries) UpsertRankingLinkShare(ctx context.Context, arg UpsertRankingLinkShareParams) (RankingShare, error) {
	row := q.db.QueryRow(ctx, upsertRankingLinkShare, arg.RankingID, arg.PublicSlug)
	var i RankingShare
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Role,
		&i.IsPublic,
		&i.PublicSlug,
		&i.UserID,
		&i.Email,
		&i.RankingID,
	)
	return i, err
}
