// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (token_hash, expires_at, user_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, sent_at, expires_at, token_hash, is_verified, user_id
`

type CreateEmailVerificationParams struct {
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UserID    int64
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.TokenHash, arg.ExpiresAt, arg.UserID)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.IsVerified,
		&i.UserID,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (token_hash, expires_at, user_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, sent_at, expires_at, token_hash, is_used, user_id
`

type CreatePasswordResetParams struct {
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UserID    int64
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.TokenHash, arg.ExpiresAt, arg.UserID)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.IsUsed,
		&i.UserID,
	)
	return i, err
}

const getEmailVerificationByTokenHash = `-- name: GetEmailVerificationByTokenHash :one
SELECT id, created_at, sent_at, expires_at, token_hash, is_verified, user_id FROM email_verifications WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByTokenHash, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.IsVerified,
		&i.UserID,
	)
	return i, err
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT id, created_at, sent_at, expires_at, token_hash, is_used, user_id FROM password_resets WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByTokenHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.IsUsed,
		&i.UserID,
	)
	return i, err
}

const redeemEmailVerification = `-- name: RedeemEmailVerification :one
UPDATE email_verifications
SET is_verified = true
WHERE token_hash = $1
  AND is_verified = false
  AND expires_at > now()
RETURNING id, created_at, sent_at, expires_at, token_hash, is_verified, user_id
`

// Marks a verification used. Returns nothing if no verification was updated
// beacuse it's expired, invalid or already used.
func (q *Queries) RedeemEmailVerification(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, redeemEmailVerification, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.IsVerified,
		&i.UserID,
	)
	return i, err
}

const redeemPasswordReset = `-- name: RedeemPasswordReset :one
UPDATE password_resets
SET is_used = true
WHERE token_hash = $1
  AND is_used = false
  AND expires_at > now()
RETURNING id, created_at, sent_at, expires_at, token_hash, is_used, user_id
`

// Same as above but for password verifications.
func (q *Queries) RedeemPasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, redeemPasswordReset, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SentAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.IsUsed,
		&i.UserID,
	)
	return i, err
}
