// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package db

import (
	"context"
)

const createRankingVersion = `-- name: CreateRankingVersion :one
INSERT INTO ranking_versions (short_uuid, ranking_id)
VALUES ($1, $2)
RETURNING id, created_at, updated_at, short_uuid, ranking_id, published_at
`

type CreateRankingVersionParams struct {
	ShortUuid string
	RankingID int64
}

func (q *Queries) CreateRankingVersion(ctx context.Context, arg CreateRankingVersionParams) (RankingVersion, error) {
	row := q.db.QueryRow(ctx, createRankingVersion, arg.ShortUuid, arg.RankingID)
	var i RankingVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortUuid,
		&i.RankingID,
		&i.PublishedAt,
	)
	return i, err
}

const getRankingVersionByShortUUID = `-- name: GetRankingVersionByShortUUID :one
SELECT id, created_at, updated_at, short_uuid, ranking_id, published_at FROM ranking_versions WHERE ranking_id = $1 AND short_uuid = $2
`

type GetRankingVersionByShortUUIDParams struct {
	RankingID int64
	ShortUuid string
}

func (q *Queries) GetRankingVersionByShortUUID(ctx context.Context, arg GetRankingVersionByShortUUIDParams) (RankingVersion, error) {
	row := q.db.QueryRow(ctx, getRankingVersionByShortUUID, arg.RankingID, arg.ShortUuid)
	var i RankingVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortUuid,
		&i.RankingID,
		&i.PublishedAt,
	)
	return i, err
}

const listDraftRankingVersionsForRankings = `-- name: ListDraftRankingVersionsForRankings :many
SELECT id, created_at, updated_at, short_uuid, ranking_id, published_at FROM ranking_versions
WHERE ranking_id = ANY($1::bigint[]) AND published_at IS NULL
`

// Feeds the rankings index: the (at most one, per the
// ranking_versions_one_draft_idx constraint) draft version for each
// ranking_id, in one query rather than N.
func (q *Queries) ListDraftRankingVersionsForRankings(ctx context.Context, rankingIds []int64) ([]RankingVersion, error) {
	rows, err := q.db.Query(ctx, listDraftRankingVersionsForRankings, rankingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingVersion
	for rows.Next() {
		var i RankingVersion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortUuid,
			&i.RankingID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublishedRankingVersionsForRankings = `-- name: ListLatestPublishedRankingVersionsForRankings :many
SELECT DISTINCT ON (ranking_id) id, created_at, updated_at, short_uuid, ranking_id, published_at
FROM ranking_versions
WHERE ranking_id = ANY($1::bigint[]) AND published_at IS NOT NULL
ORDER BY ranking_id, published_at DESC
`

// Feeds the rankings index: one row per ranking_id, its most recently
// published version. DISTINCT ON (ranking_id) with this ordering picks the
// newest publish per ranking in a single scan, so the index can describe N
// rankings' live-published state in one query rather than N.
func (q *Queries) ListLatestPublishedRankingVersionsForRankings(ctx context.Context, rankingIds []int64) ([]RankingVersion, error) {
	rows, err := q.db.Query(ctx, listLatestPublishedRankingVersionsForRankings, rankingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingVersion
	for rows.Next() {
		var i RankingVersion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortUuid,
			&i.RankingID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingVersionsForRanking = `-- name: ListRankingVersionsForRanking :many
SELECT id, created_at, updated_at, short_uuid, ranking_id, published_at FROM ranking_versions WHERE ranking_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRankingVersionsForRanking(ctx context.Context, rankingID int64) ([]RankingVersion, error) {
	rows, err := q.db.Query(ctx, listRankingVersionsForRanking, rankingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingVersion
	for rows.Next() {
		var i RankingVersion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortUuid,
			&i.RankingID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishRankingVersion = `-- name: PublishRankingVersion :one
UPDATE ranking_versions
SET published_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, created_at, updated_at, short_uuid, ranking_id, published_at
`

func (q *Queries) PublishRankingVersion(ctx context.Context, id int64) (RankingVersion, error) {
	row := q.db.QueryRow(ctx, publishRankingVersion, id)
	var i RankingVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortUuid,
		&i.RankingID,
		&i.PublishedAt,
	)
	return i, err
}

const resolveLiveRankingVersion = `-- name: ResolveLiveRankingVersion :one
SELECT id, created_at, updated_at, short_uuid, ranking_id, published_at FROM ranking_versions
WHERE ranking_id = $1
ORDER BY published_at DESC NULLS LAST
LIMIT 1
`

// The live ranking is the most recenly published one. If no rankings are published,
// we use the draft.
func (q *Queries) ResolveLiveRankingVersion(ctx context.Context, rankingID int64) (RankingVersion, error) {
	row := q.db.QueryRow(ctx, resolveLiveRankingVersion, rankingID)
	var i RankingVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortUuid,
		&i.RankingID,
		&i.PublishedAt,
	)
	return i, err
}
